# List the ports you want to expose and what to do when they are served.
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks.
tasks:
  - init: mvn -Dmaven.repo.local=.m2 install -Dsuite=parallel.xml # runs during prebuild
    command: echo 'Please check your test on https://hyperexecute.lambdatest.com/'